"""The training environment, as a file DVC can depend on.

    python3 scripts/training_env.py          # rewrite configs/training_env.txt
    python3 scripts/training_env.py --check  # exit 1 if it is stale

Models are trained and evaluated in the Dockerfile's ``train`` target
(``scripts/train_env.sh``): its pinned base image decides glibc/libm, and so
the last bits of features such as ``np.hypot``. That definition lives in the
Dockerfile, which DVC does not read, so changing the base image used to leave
every stage "up to date" with outputs produced under the old environment.

``configs/training_env.txt`` is the part of the Dockerfile that builds the
``train`` target - the ``train`` stage, every stage it copies from, and the
global ARGs they use - with comments and blank lines dropped. Every DVC stage
depends on it, ``train_env.sh`` keys its image on it (with ``uv.lock``) and
refuses to run when it is stale, and a test keeps it equal to the Dockerfile.
A serving-only Dockerfile edit (runtime stage, Lambda adapter) changes
nothing here and retrains nothing. Standard library only: it runs on the host
before any environment exists.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCKERFILE = ROOT / "Dockerfile"
OUT = ROOT / "configs" / "training_env.txt"
TARGET = "train"
HEADER = (
    "# Generated by scripts/training_env.py from the Dockerfile: the build of the\n"
    f"# `{TARGET}` target. Every DVC stage depends on this file. Do not edit;\n"
    "# regenerate after changing the Dockerfile.\n"
)

FROM = re.compile(r"^FROM\s+(?:--\S+\s+)*(\S+)(?:\s+AS\s+(\S+))?\s*$", re.IGNORECASE)
COPY_FROM = re.compile(r"--from=(\S+)")
VAR = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)")


def _logical_lines(text: str) -> list[str]:
    """Instructions with backslash continuations joined; no comments/blanks."""
    out: list[str] = []
    buf = ""
    for raw in text.splitlines():
        line = raw.strip()
        if not buf and (not line or line.startswith("#")):
            continue
        if line.startswith("#"):  # a comment line inside a continuation
            continue
        # Mid-line "#" is not a Dockerfile comment (the shell sees it): kept.
        if line.endswith("\\"):
            buf += line[:-1].rstrip() + " "
            continue
        out.append((buf + line).strip())
        buf = ""
    if buf:
        out.append(buf.strip())
    return out


def training_env(dockerfile: str, target: str = TARGET) -> str:
    lines = _logical_lines(dockerfile)
    global_args: dict[str, str] = {}
    stages: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in lines:
        m = FROM.match(line)
        if m:
            current = [line]
            stages[m.group(2) or f"#{len(stages)}"] = current
        elif current is None:
            if line.upper().startswith("ARG "):
                name = line[4:].split("=", 1)[0].strip()
                global_args[name] = line
        else:
            current.append(line)
    if target not in stages:
        raise SystemExit(f"Dockerfile has no stage named {target!r}")

    needed: list[str] = []
    todo = [target]
    while todo:
        name = todo.pop()
        if name in needed or name not in stages:
            continue
        needed.append(name)
        body = stages[name]
        todo += COPY_FROM.findall("\n".join(body))
        base = FROM.match(body[0])
        if base and base.group(1) in stages:
            todo.append(base.group(1))
    used = {v for name in needed for line in stages[name] for v in VAR.findall(line)}
    args = [line for name, line in global_args.items() if name in used]
    # Dockerfile order, so the file reads like the Dockerfile it came from.
    order = list(stages)
    blocks = ["\n".join(stages[n]) for n in sorted(needed, key=order.index)]
    return HEADER + "\n".join(args) + "\n\n" + "\n\n".join(blocks) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if stale")
    args = ap.parse_args(argv)
    want = training_env(DOCKERFILE.read_text())
    have = OUT.read_text() if OUT.exists() else ""
    if args.check:
        if have != want:
            print(
                f"{OUT.relative_to(ROOT)} is stale against the Dockerfile's "
                f"`{TARGET}` target: run python3 scripts/training_env.py and commit "
                "it (every DVC stage re-runs: the training environment changed)",
                file=sys.stderr,
            )
            return 1
        return 0
    if have != want:
        OUT.write_text(want)
        print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
